### ISSUE TITLE
Minizip compile error

### ISSUE THREAD

**Issue by ROV28** [domoticz/minizip#4]
Dear all,

I encounter an error while compiling minizip:
```
/domoticz/extern/minizip/zip.c: In function ‘zipOpenNewFileInZip4_64’:
/domoticz/extern/minizip/zip.c:1248:28: error: assignment to ‘const long unsigned int *’ from incompatible pointer type ‘const uint32_t *’ {aka ‘const unsigned int *’} [-Wincompatible-pointer-types]
 1248 |         zi->ci.pcrc_32_tab = get_crc_table();
```

System is Fedora 40.

BR,
R

**Comment by gizmocuz** [comment]
Question, did you follow this guide to the letter?

https://www.domoticz.com/wiki/Build_Domoticz_from_source

**Comment by ROV28** [comment]
Based on that guide I build a script way back and used is dozend times, it stopped working with the error. I guess it due an update of some tool or lib.

**Comment by gizmocuz** [comment]
Could you move your build folder to a backup location and follow the above guide to the letter?
(It could be that a library dependency needs to be updated on your system, but first follow the above guide)

**Comment by ROV28** [comment]
I have followed the guide, libsqlite3x-devel and ghc-cereal-devel  were missing, but... it makes not difference. I got exactly the same error 

`    make: 4.4.1
    gcc: 14.1.1
    g++: 14.1.1
    openssl-devel: 1:3.2.1-2
    git: 2.45.2
    libcurl-devel: 8.6.0-8
    libusb1-devel: 1.0.27-2
    INSTALLED: libsqlite3x-devel: 20071018-36
    python3-devel: 3.12.3-2
    zlib-ng-compat-devel: 2.1.6-5
    INSTALLED: ghc-cereal-devel 0.5.8.3-6.
    lua-devel: 5.4.6-5
    lua-libs: 5.4.6-5
    uthash-devel: 2.3.0-7
    wget: 2.1.0
`

**Comment by gizmocuz** [comment]
I removed the cereal library from the wiki, that is not needed anymore

But your system is installing/using a sqlite3 library from 2007?

As it seems you are the only one with this compile issue, I want to suggest a few options:

- Use the precompiled version, is there a need to compile? (Unless you want to contribute some code)
- Use the docker build environment (https://github.com/domoticz/domoticz/tree/development/build)
- Patch the minizip library (https://github.com/domoticz/minizip)

**Comment by ROV28** [comment]
No clue why it is numbered like this, SQLite looks newer:
`SQLite version 3.45.1 2024-01-30 16:01:20`

Regarding the options:
- For curiosity and staying up-to-date
- Only little (less successful) experience with docker containers, will cost too much time
- That is beyond my programming skills (I guess)

I will wait, Fedora is at the forefront with releases, the others will follow and then this issues pops up again, probably...

**Comment by gizmocuz** [comment]
Ok, until then, just use the binary install/beta to stay up to date
